[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = min_spiffs.csv
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    vshymanskyy/TinyGSM @ ^0.11.7
    knolleary/PubSubClient @ ^2.8
    adafruit/RTClib @ ^2.1.1
    https://github.com/Abdurraziq/ZMPT101B-arduino.git
